### ISSUE TITLE
Could not find a relationship between 'products' and 'prices' in the schema cache

### ISSUE THREAD

**Issue by PatelN123** [vercel/nextjs-subscription-payments#140]
Hi,

I get the above error, with:

```
info  - Linting and checking validity of types...
07:28:32.396 | info  - Creating an optimized production build...
07:28:44.919 | info  - Compiled successfully
07:28:44.920 | info  - Collecting page data...
07:28:48.198 | info  - Generating static pages (0/5)
07:28:48.261 | info  - Generating static pages (1/5)
07:28:48.270 | info  - Generating static pages (2/5)
07:28:48.274 | info  - Generating static pages (3/5)
07:28:48.672 | Could not find a relationship between 'products' and 'prices' in the schema cache
07:28:48.673 | info  - Generating static pages (5/5)
07:28:48.673 |  
07:28:48.674 | Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
07:28:48.674 | [object Object]
07:28:48.674 |  
07:28:48.675 | > Build error occurred
07:28:48.677 | Error: Export encountered errors on following paths:
07:28:48.678 | /
07:28:48.678 | at /vercel/path0/node_modules/next/dist/export/index.js:394:19
07:28:48.679 | at runMicrotasks (<anonymous>)
07:28:48.679 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
07:28:48.679 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
07:28:48.680 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
07:28:48.680 | at async /vercel/path0/node_modules/next/dist/build/index.js:1044:17
07:28:48.680 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
07:28:48.681 | at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:65:29)
07:28:48.718 | error Command failed with exit code 1.
07:28:48.719 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
07:28:48.743 | Error: Command "yarn run build" exited with 1
```

Please advise how I can resolve this.

**Comment by nextboringai** [comment]
same error.... i need help please :(, and also, when i wanna add supabase as integration, it shows a pop up, but do nothing.

**Comment by nabilfatih** [comment]
i had same error as well... i was cloning this repo like 1 month ago, and it still works fine. but i cloning this repo again, and it doesnt work... and also, when i wanna add supabase as integration, it gives me a pop up into supabase, but do nothing. i have cleared my cache but it gives me nothing.

Anyone know how to solve this? really need help :(

**Comment by thorwebdev** [comment]
Sorry to hear that you're running into this! Investigating now.

**Comment by BirbEXE** [comment]
same here :3

**Comment by BirbEXE** [comment]
> There was an issue with our vercel integration, sorry about that. This has been fixed now, please retry.

it seems the commit that fixed this no longer exists???
I can see in my logs that you created and deleted it

did it not work?

**Comment by thorwebdev** [comment]
Our vercel integration is in a different repository. Not sure what commit you're referring to.

**Comment by karuzo17** [comment]
@thorwebdev for me, it still doesn't work. I cloned the repo again, but still the same error message.

**Comment by BirbEXE** [comment]
Same here

**Comment by thorwebdev** [comment]
Have you made sure to set up the schema in Supabase? 

Did you use the Deploy button in the readme https://github.com/vercel/nextjs-subscription-payments#deploy-with-vercel and went through the supabase deploy integration in there? That sets up the schema for you. (that part was broken and is now fixed)

If you're not using the deploy button you will need to set up the schema yourself, e.g. via the Stripe Subscriptions quickstart in the SQL editor: https://app.supabase.com/project/_/sql
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/5748289/203914117-02572944-0ea1-4022-967f-3d4b9bb3c004.png">

**Comment by bharathvaj-ganesan** [comment]
Is this mentioned in the readme doc ?

**Comment by olingern** [comment]
This appears to still have issues

JSON error from Vercel `push-to-repo` endpoint
```json
{"error":{"code":"bad_request","message":"Invalid request: missing required property `source`."}}
```

<img width="900" alt="image" src="https://github.com/vercel/nextjs-subscription-payments/assets/1470297/cf3cae53-2ec9-493f-864e-8e4e62d94931">
